version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bustrackr
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: "neo4j/neo4jpassword"
    ports: ["7474:7474","7687:7687"]
    volumes:
      - neo4jdata:/data

volumes:
  pgdata:
  neo4jdata:
